package net.github.creep3rcrafter.inspire.register;

import dev.architectury.registry.registries.DeferredRegister;
import net.github.creep3rcrafter.inspire.InspireCommon;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.JukeboxSong;

public class InspireJukeBoxSongs {
    public static final DeferredRegister<JukeboxSong> JUKEBOX_SONGS = DeferredRegister.create(InspireCommon.MOD_ID, Registries.JUKEBOX_SONG);
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_A_FAMILIAR_ROOM;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_AERIE;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_ANCESTRY;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_ARIA_MATH;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_BIOME_FEST;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_BLIND_SPOTS;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_CLARK;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_COMFORTING_MEMORIES;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_DANNY;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_DREITON;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_DRY_HANDS;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_FEATHERFALL;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_FLOATING_DREAM;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_HAGGSTROM;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_HAUNT_MUSKIE;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_KEY;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_KOMOREBI;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_LEFT_TO_BLOOM;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_LIVING_MICE;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_MICE_ON_VENUS;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_MINECRAFT;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_ONE_MORE_DAY;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_OXYGENE;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_PUZZLEBOX;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_SUBWOOFER_LULLABY;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_SWEDEN;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_TASWELL;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_WATCHER;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_WET_HANDS;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_YAKUSOKU;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_BALLAD_OF_THE_CATS;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_CHRYSAPOEIA;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_CONCRETE_HALLS;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_DEAD_VOXEL;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_RUBEDO;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_SO_BELOW;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_WARMTH;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_BOSS;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_ALPHA;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_THE_END;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_BEGINNING_2;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_BROMELIAD;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_ECHO_IN_THE_WIND;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_ELD_UNKNOWN;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_AN_ORDIANRY_DAY;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_BELOW_AND_ABOVE;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_BROKEN_CLOCKS;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_CRESCENT_DUNES;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_FIREBUGS;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_FIREFLIES;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_INFINITE_AMETHYST;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_LABYRINTHINE;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_LILYPAD;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_OS_PIANO;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_STAND_TALL;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_WENDING;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_AXOLOTL;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_DRAGON_FISH;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_SHUNIJI;
    public static final ResourceKey<JukeboxSong> MUSIC_DISC_DEEPER;

    static {
        MUSIC_DISC_A_FAMILIAR_ROOM = create("music_disc_a_familiar_room");
        MUSIC_DISC_AERIE = create("music_disc_aerie");
        MUSIC_DISC_ANCESTRY = create("music_disc_ancestry");
        MUSIC_DISC_ARIA_MATH = create("music_disc_aria_math");
        MUSIC_DISC_BIOME_FEST = create("music_disc_biome_fest");
        MUSIC_DISC_BLIND_SPOTS = create("music_disc_blind_spots");
        MUSIC_DISC_CLARK = create("music_disc_clark");
        MUSIC_DISC_COMFORTING_MEMORIES = create("music_disc_comforting_memories");
        MUSIC_DISC_DANNY = create("music_disc_danny");
        MUSIC_DISC_DREITON = create("music_disc_dreiton");
        MUSIC_DISC_DRY_HANDS = create("music_disc_dry_hands");
        MUSIC_DISC_FEATHERFALL = create("music_disc_featherfall");
        MUSIC_DISC_FLOATING_DREAM = create("music_disc_floating_dream");
        MUSIC_DISC_HAGGSTROM = create("music_disc_haggstrom");
        MUSIC_DISC_HAUNT_MUSKIE = create("music_disc_haunt_muskie");
        MUSIC_DISC_KEY = create("music_disc_key");
        MUSIC_DISC_KOMOREBI = create("music_disc_komorebi");
        MUSIC_DISC_LEFT_TO_BLOOM = create("music_disc_left_to_bloom");
        MUSIC_DISC_LIVING_MICE = create("music_disc_living_mice");
        MUSIC_DISC_MICE_ON_VENUS = create("music_disc_mice_on_venus");
        MUSIC_DISC_MINECRAFT = create("music_disc_minecraft");
        MUSIC_DISC_ONE_MORE_DAY = create("music_disc_one_more_day");
        MUSIC_DISC_OXYGENE = create("music_disc_oxygene");
        MUSIC_DISC_PUZZLEBOX = create("music_disc_puzzlebox");
        MUSIC_DISC_SUBWOOFER_LULLABY = create("music_disc_subwoofer_lullaby");
        MUSIC_DISC_SWEDEN = create("music_disc_sweden");
        MUSIC_DISC_TASWELL = create("music_disc_taswell");
        MUSIC_DISC_WATCHER = create("music_disc_watcher");
        MUSIC_DISC_WET_HANDS = create("music_disc_wet_hands");
        MUSIC_DISC_YAKUSOKU = create("music_disc_yakusoku");
        MUSIC_DISC_BALLAD_OF_THE_CATS = create("music_disc_ballad_of_the_cats");
        MUSIC_DISC_CHRYSAPOEIA = create("music_disc_chrysopoeia");
        MUSIC_DISC_CONCRETE_HALLS = create("music_disc_concrete_halls");
        MUSIC_DISC_DEAD_VOXEL = create("music_disc_dead_voxel");
        MUSIC_DISC_RUBEDO = create("music_disc_rubedo");
        MUSIC_DISC_SO_BELOW = create("music_disc_so_below");
        MUSIC_DISC_WARMTH = create("music_disc_warmth");
        MUSIC_DISC_BOSS = create("music_disc_boss");
        MUSIC_DISC_ALPHA = create("music_disc_alpha");
        MUSIC_DISC_THE_END = create("music_disc_the_end");
        MUSIC_DISC_BEGINNING_2 = create("music_disc_beginning_2");
        MUSIC_DISC_BROMELIAD = create("music_disc_bromeliad");
        MUSIC_DISC_ECHO_IN_THE_WIND = create("music_disc_echo_in_the_wind");
        MUSIC_DISC_ELD_UNKNOWN = create("music_disc_eld_unknown");
        MUSIC_DISC_AN_ORDIANRY_DAY = create("music_disc_an_ordinary_day");
        MUSIC_DISC_BELOW_AND_ABOVE = create("music_disc_below_and_above");
        MUSIC_DISC_BROKEN_CLOCKS = create("music_disc_broken_clocks");
        MUSIC_DISC_CRESCENT_DUNES = create("music_disc_crescent_dunes");
        MUSIC_DISC_FIREBUGS = create("music_disc_firebugs");
        MUSIC_DISC_FIREFLIES = create("music_disc_fireflies");
        MUSIC_DISC_INFINITE_AMETHYST = create("music_disc_infinite_amethyst");
        MUSIC_DISC_LABYRINTHINE = create("music_disc_labyrinthine");
        MUSIC_DISC_LILYPAD = create("music_disc_lilypad");
        MUSIC_DISC_OS_PIANO = create("music_disc_os_piano");
        MUSIC_DISC_STAND_TALL = create("music_disc_stand_tall");
        MUSIC_DISC_WENDING = create("music_disc_wending");
        MUSIC_DISC_AXOLOTL = create("music_disc_axolotl");
        MUSIC_DISC_DRAGON_FISH = create("music_disc_dragon_fish");
        MUSIC_DISC_SHUNIJI = create("music_disc_shuniji");
        MUSIC_DISC_DEEPER = create("music_disc_deeper");
    }
    private static ResourceKey<JukeboxSong> create(String string) {
        return ResourceKey.create(Registries.JUKEBOX_SONG, ResourceLocation.fromNamespaceAndPath(InspireCommon.MOD_ID, string));
    }
}
