org.gradle.jvmargs=-Xmx6G -Xms2G -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.incremental=true
org.gradle.workers.max=8
fabric.loom.multiProjectOptimisation=true
# Mod properties
mod_version = 1.0.0
maven_group = net.github.creep3rcrafter.inspire
archives_name = inspire
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.11
fabric_loader_version = 0.19.3
fabric_api_version = 0.116.12+1.21.1
neoforge_version = 21.1.215
