org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = net.github.creep3rcrafter.inspire
archives_name = inspire
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.19.3
fabric_api_version = 0.116.12+1.21.1
neoforge_version = 21.1.215
